#!/bin/sh

. ./_200-headers.sh

# Guillemets : nu, ?* faisait globber le dossier, et une requête sans argument laissait
# cat lire son entrée standard. basename suffit à interdire la remontée de chemin.
/usr/bin/cat "$(basename "${QUERY_STRING}")"
